### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by matkoniecz**
(BTW, what would be a good kotlin library for parsing Kotlin code if that is not intended to be used)

### CODE REVIEW

**Comment by 2bad2furious** [comment]
I have personally used [kotlinx/ast](https://github.com/kotlinx/ast)

**Comment by matkoniecz** [comment]
@2bad2furious Do you have, by any chance, some simple working open-source project? Likely it is problem on my side, but I cannot get it to work - https://github.com/kotlinx/ast/issues/63#issuecomment-1184113453

**Comment by 2bad2furious** [comment]
Try [this](https://github.com/2bad2furious/kotlinx-ast-demo) one.
I had to comment out the implementation in build.gradle.kts, import it and then uncomment it and import it again.

**Comment by matkoniecz** [comment]
Thanks! It worked with minor tweaks (making gradlew executable, adding gradle folder), but this time I was capable of doing them :)

Thanks again!

**Pull request merged**
